### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by yashjawale** [slidesync/slidesync-web#1]

**Comment by mademoiselle-chantal** [comment]
Hello, @yashjawale. Can l work on this issue?

**Comment by yashjawale** [comment]
Yeah Sure!
Let me know if you need help with anything

**Comment by mademoiselle-chantal** [comment]
> Yeah Sure! Let me know if you need help with anything

Thank you. If l may ask, what exactly needs to be improved on the readme?

**Comment by yashjawale** [comment]
For now, just instructions to run the project locally are enough ig.

**Comment by yashjawale** [comment]
We are in the process of setting up CI/CD pipelines, releases etc & will add other stuff later

**Comment by mademoiselle-chantal** [comment]
> For now, just instructions to run the project locally are enough ig.

Alright, well understood.

**Comment by mademoiselle-chantal** [comment]
@yashjawale The PR for this work is ready. Feel free to let me know if you need me to edit anything.
